### ISSUE TITLE
Error with ESX version

### ISSUE THREAD

**Issue by SamBradley123** [cadburry6969/cad-email#1]
Hello,
first of all thank you for this script!

When I use it and specify the user id it gives me the error below.

On the other hand when I use the discord ID it works

![image](https://user-images.githubusercontent.com/69010639/151236553-011db0c0-521c-43bd-9d62-34c091c7e33e.png)

**Comment by cadburry6969** [comment]
What fields you had filled?

**Comment by SamBradley123** [comment]
Hello, sorry for my late response.

First I tried the discord ID and it worked, then I wrote in ALL the fields except the Discord ID (person id, subject, and message)

**Comment by cadburry6969** [comment]
Can you try applying the recent commit and check if the issue still persists
