### ISSUE TITLE
Freeze

### ISSUE THREAD

**Issue by Honzix2306** [cadburry6969/cad-email#2]
Hi, I just want to know, what should I do, when I use command and the char freezes. Im developer on fivem qb core server.

**Comment by cadburry6969** [comment]
you may have changed the resource name and forgot to change the post request in index.html
anyways use this commit https://github.com/cadburry6969/cad-email/commit/f540071f75a2bee617debaceb163816ff889fe9c

If not the above then you may have missed something or not configured it properly
